# ~/nixos-config/hosts/aj-laptop/default.nix
{ inputs, pkgs, lib, config, unstablePkgs, ... }:

{
  imports = [
    # Import the hardware profile for the Zephyrus G14 (GA401 model)
    inputs.nixos-hardware.nixosModules.asus-zephyrus-ga401

    # Hardware-specific configuration generated for this host.
    # Will be regenerated by the install script.
    ./hardware-configuration.nix

    # Disko disk layout
    ./disko-config.nix

    # Top level nixos modules import.
    ../../modules/nixos/default.nix
  ];

  customConfig = {

    user = {
      name = "aj";
      email = "aj@example.com"; # TODO: update before install
    };

    bootloader = {
      quietBoot = true;
      plymouth = {
        enable = true;
        theme = "green_blocks"; # placeholder — change after install
      };
    };

    system = {
      hostName = "aj-laptop";
      stateVersion = "25.05"; # DO NOT CHANGE
      timeZone = "America/Los_Angeles";
      locale = "en_US.UTF-8";
    };

    desktop = {
      environments = [ "kde" ];
      displayManager = {
        enable = true;
        type = "sddm";
        sddm = {
          theme = "sddm-astronaut";
          embeddedTheme = "pixel_sakura"; # placeholder — change after install
          screensaver = {
            enable = true;
            timeout = 10;
          };
        };
      };
    };

    hardware = {
      unstable = true;
      nvidia = {
        enable = true;
        laptop = {
          enable = true;
          amdgpuID = "PCI:4:0:0"; # placeholder — confirm after install
          nvidiaID = "PCI:1:0:0"; # placeholder — confirm after install
        };
      };
      display.backlight.enable = true;
      kbdBacklight.enable = true;
    };

    homeManager = {
      enable = true;
      themes = {
        kde = "none";
      };
    };

    packages = {
      nixos = with pkgs; [];
      unstable-override = [
        "discord-canary"
        "brave"
      ];
      homeManager = with pkgs; [
        brave
        chromium
        discord-canary
      ];
      flatpak = {
        enable = true;
        packages = [
          "com.spotify.Client"
        ];
      };
    };

    profiles = {
      gaming.enable = true;
    };

    services = {
      ssh.enable = false;
      vscodeServer.enable = false;
    };

  };

  # Flatpak support
  services.flatpak.enable = true;

  # Home Manager configuration for this host
  home-manager = lib.mkIf config.customConfig.homeManager.enable {
    useGlobalPkgs = true;
    useUserPackages = true;
    backupFileExtension = "hm-backup";
    overwriteBackup = true;
    extraSpecialArgs = { inherit inputs unstablePkgs; customConfig = config.customConfig; };
    users.${config.customConfig.user.name} = {
      imports = [
        # === Plasma Manager ===
        inputs.plasma-manager.homeModules.plasma-manager
        # === Common User Environment Modules ===
        ../../modules/home-manager/default.nix
      ];
    };
  };

}
