# ~/nixos-config/modules/home-manager/themes/century-series/night-mode.nix
#
# century-night: swaps the century-series theme between its DAY palette and its
# NIGHT (F-117/B-2 stealth cockpit) palette, animated, on the same sunset
# boundary hyprsunset uses.
#
#   century-night init       apply the right palette instantly (login, activation)
#   century-night status     MODE, phase, and which side of the boundary we are on
#   century-night day|night  pin a palette and ramp to it
#   century-night auto       follow the sun again
#   century-night toggle     flip to the other side (pins a manual mode)
#   century-night reconcile  run the reconciler now
#
# Structure is deliberately a copy of scripts/hyprsunset-control.nix, because
# that module already solved this problem shape:
#   century-night-schedule.service  oneshot reconciler, run every 5 min by its
#     timer. Works out the target from hyprsunset-isday and hands a GRADUAL
#     transition to the ramp whenever the applied phase does not match. Polling
#     rather than firing at the boundary is what makes it self-healing: it also
#     catches resume-from-suspend, a crash, and a mode change.
#   century-night-ramp.service      the walk itself, in the FOREGROUND so
#     systemd owns its lifecycle — `restart` retargets, `stop` cancels. Unlike
#     hyprsunset-transition this backgrounds nothing, so it keeps the default
#     KillMode and avoids that module's orphaned-`sleep` wart.
#
# State (~/.cache/), kept INDEPENDENT of hyprsunset's: its reconciler exits
# early when its own mode is manual/disabled, so piggybacking on it would mean
# the theme silently stopped switching the moment someone scrolled that widget.
#   century-night-state   MODE: auto | day | night
#   century-night-phase   step index currently applied (0 = day, N = night)
#   century-night-target  step index the ramp is walking to
#   century-night-shader  path of the current-phase CRT shader, read by
#                         century-crt-toggle so the opt-in filter matches
#
# The boundary itself is NOT reimplemented here: hyprsunset-solar.nix is the
# single source of truth (its header records that this arithmetic was once
# copy-pasted into five scripts). It is referenced by absolute store path, not
# $PATH, because that binary is only in home.packages when hyprsunset is
# enabled — and night mode must work when it is not.
{ config, pkgs, lib, customConfig, ... }:

with lib;

let
  colorsModule = import ./colors.nix { };
  crtShaders = import ./crt-shader.nix { };

  cfg = customConfig.homeManager.themes.centurySeries.night;
  sunCfg = customConfig.homeManager.services.hyprsunset;

  centurySeriesThemeCondition = lib.elem "hyprland" customConfig.desktop.environments
    && customConfig.homeManager.themes.hyprland == "century-series";
  enabled = centurySeriesThemeCondition && cfg.enable;

  # N steps => N+1 palettes, endpoints exact (see colors.nix).
  steps = cfg.steps;
  palettes = colorsModule.paletteSteps steps;
  lastStep = steps;

  isDay = "${import ../../scripts/hyprsunset-solar.nix {
    inherit pkgs;
    cfg = sunCfg;
  }}/bin/hyprsunset-isday";

  systemctl = "${pkgs.systemd}/bin/systemctl";
  hyprctl = "${pkgs.hyprland}/bin/hyprctl";

  homeDir = config.home.homeDirectory;
  paletteLive = "${homeDir}/.config/waybar/century-palette.css";
  stateFile = "${homeDir}/.cache/century-night-state";
  phaseFile = "${homeDir}/.cache/century-night-phase";
  targetFile = "${homeDir}/.cache/century-night-target";
  shaderFile = "${homeDir}/.cache/century-night-shader";

  # ---- generated artifacts -------------------------------------------------
  # GTK named colours. @define-color takes #rrggbb or rgba() but REJECTS
  # 8-digit hex, so anything carrying alpha is emitted as rgba().
  cssName = n: "c_" + builtins.replaceStrings [ "-" ] [ "_" ] n;
  defineColor = n: hex:
    let v = colorsModule.rgbaOf hex;
    in if v.a >= 1.0
       then "@define-color ${cssName n} ${builtins.substring 0 7 hex};"
       else "@define-color ${cssName n} rgba(${toString v.r}, ${toString v.g}, ${toString v.b}, ${toString v.a});";

  mkPaletteCss = pal: ''
    /* century-series palette — GENERATED by night-mode.nix, rewritten on every
       ramp step. Do not edit: your changes will be overwritten within 5
       minutes. Edit colors.nix instead. */
  '' + concatStringsSep "\n" (mapAttrsToList defineColor pal) + "\n";

  lerpF = a: b: t: a + (b - a) * t;
  tAt = i: i * 1.0 / (lastStep * 1.0);
  # Night is dimmer, not just redder.
  dimAt = i: lerpF 0.15 0.30 (tAt i);
  brightAt = i: lerpF 0.95 0.80 (tAt i);
  blueAttenAt = i: lerpF 1.0 0.55 (tAt i);

  sh = s: removePrefix "#" s;

  mkStep = i:
    let
      p = elemAt palettes i;
      css = pkgs.writeText "century-palette-${toString i}.css" (mkPaletteCss p);
      shader = pkgs.writeText "century-crt-${toString i}.glsl"
        (crtShaders.mkCrtBarrelShader p (blueAttenAt i));
    in pkgs.writeShellScript "century-night-step-${toString i}" ''
      set -u
      # $1 selects which half to apply:
      #   all   (default) files + compositor — login, activation, re-assert
      #   files palette + shader pointer only
      #   live  compositor keywords only — what each ramp step uses
      # The split exists because waybar can only be restyled by a reload, and a
      # reload cannot happen once per step (see the ramp script).
      STEP_MODE="''${1:-all}"

      if [ "$STEP_MODE" != live ]; then
        # Only write when the content actually differs. The 5-minute reconciler
        # re-asserts the current step even when nothing changed, and an
        # unconditional write would bump the mtime every 5 minutes forever.
        #
        # Atomic rename, never an in-place write: GTK must not see a truncated
        # palette, and ANY parse error rejects the whole provider (unstyled bars).
        if ! ${pkgs.diffutils}/bin/cmp -s ${css} "${paletteLive}"; then
          ${pkgs.coreutils}/bin/install -m644 ${css} "${paletteLive}.new"
          ${pkgs.coreutils}/bin/mv -f "${paletteLive}.new" "${paletteLive}"
        fi

        echo "${shader}" > "${shaderFile}"
      fi

      [ "$STEP_MODE" = files ] && exit 0

      # Everything below needs a live compositor, and hyprctl needs
      # HYPRLAND_INSTANCE_SIGNATURE — which is NOT in the systemd user
      # environment: hyprland/functional.nix imports only WAYLAND_DISPLAY,
      # DISPLAY, XDG_CURRENT_DESKTOP and XDG_MENU_PREFIX via
      # dbus-update-activation-environment. Without this discovery the ramp
      # would run from its service, repaint the bar, and silently never touch a
      # single border. Same approach as the claude-rwr widget in waybar.nix.
      if [ -z "''${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
        export XDG_RUNTIME_DIR="''${XDG_RUNTIME_DIR:-/run/user/$(${pkgs.coreutils}/bin/id -u)}"
        shopt -s nullglob
        for entry in "$XDG_RUNTIME_DIR"/hypr/*; do
          name="$(${pkgs.coreutils}/bin/basename "$entry")"
          case "$name" in *.lock) continue ;; esac
          if [ -d "$entry" ]; then export HYPRLAND_INSTANCE_SIGNATURE="$name"; break; fi
        done
        shopt -u nullglob
      fi
      [ -z "''${HYPRLAND_INSTANCE_SIGNATURE:-}" ] && exit 0

      # One batch so all four land in the same frame. NOTE: deliberately NOT
      # ramping `windowrule border_color` — `hyprctl keyword windowrule`
      # APPENDS rather than replaces, so ramping it would leak ~48 dead rules
      # into the rule list every day.
      ${hyprctl} --batch "\
        keyword general:col.inactive_border rgb(${sh p.border-primary}) ; \
        keyword general:col.active_border rgb(${sh p.accent-amber}) rgb(${sh p.border-active}) 45deg ; \
        keyword decoration:dim_strength ${toString (dimAt i)} ; \
        keyword decoration:blur:brightness ${toString (brightAt i)}" >/dev/null 2>&1 || true

      # Restyle the CRT filter only when it is already on (it is opt-in).
      # A DIFFERENT path per step is required: Hyprland caches the compiled
      # shader by path, so rewriting one file in place would not recompile.
      CUR=$(${hyprctl} getoption decoration:screen_shader 2>/dev/null \
            | ${pkgs.gnugrep}/bin/grep "str:" | ${pkgs.gawk}/bin/awk '{print $2}')
      if [ -n "$CUR" ] && [ "$CUR" != "[[EMPTY]]" ]; then
        ${hyprctl} keyword decoration:screen_shader "${shader}" >/dev/null 2>&1 || true
      fi
    '';

  stepScripts = genList mkStep (steps + 1);

  # usage: apply-step <index> [all|files|live]
  applyStep = pkgs.writeShellScript "century-night-apply-step" ''
    case "$1" in
    ${concatStringsSep "\n    " (imap0 (i: s: "${toString i}) exec ${s} \"\${2:-all}\" ;;") stepScripts)}
      *) echo "century-night: no such step: $1" >&2; exit 1 ;;
    esac
  '';

  # Restyle waybar. SIGUSR2 is the ONLY thing that works here, and it must be
  # used sparingly:
  #   * `reload_style_on_change` does NOT fire for @imported files — verified in
  #     a live session, both for an atomic rename and an in-place append. The
  #     top-level stylesheet is an immutable store symlink, so it never changes
  #     either, which makes that option useless for this and it is not set.
  #   * SIGUSR2 is a full reload that recreates the bars. ONE is clean; eleven
  #     in a row (one per ramp step) made both bars disappear entirely.
  # So the palette crosses over exactly once per transition, at the midpoint of
  # the ramp, while the compositor colours keep interpolating around it.
  # No -x: under the NixOS wrapper the comm is `.waybar-wrapped`.
  reloadWaybar = "${pkgs.procps}/bin/pkill -SIGUSR2 waybar 2>/dev/null || true";

  # NOTE: waybar is restyled with SIGUSR2 (see reloadWaybar), never RTMIN+N.
  # Nothing subscribes to a night-mode refresh signal yet, and an unhandled
  # realtime signal TERMINATES the target, so the per-widget refresh poke
  # returns only alongside the custom/century-night widget that configures the
  # signal (and must be checked against a live waybar then).

  # ---- wallpaper ----------------------------------------------------------
  # usage: century-wallpaper-apply <day|night> <fade-seconds>
  #
  # One call per transition, fired up front by the ramp: awww runs its own GPU
  # crossfade over the same duration, so the wallpaper fade and the compositor
  # walk overlap instead of queueing. K calls would fight each other.
  wallpaperSets = import ./wallpapers.nix {
    inherit lib customConfig;
    homeDir = homeDir;
  };

  # Day and night assignment lists are parallel — same monitors, same order —
  # so they zip into one try_set line per display.
  wallpaperLines = concatStringsSep "\n" (imap0 (i: d:
    let n = elemAt wallpaperSets.nightAssignments i;
    in ''try_set "${d.monitor}" "${d.path}" "${n.path}"''
  ) wallpaperSets.dayAssignments);

  wallpaperScript = pkgs.writeShellScriptBin "century-wallpaper-apply" ''
    set -u
    SIDE="''${1:-day}"
    DUR="''${2:-0}"
    [ "''${XDG_CURRENT_DESKTOP:-}" != "Hyprland" ] && exit 0
    ${lib.optionalString (customConfig.desktop.hyprland.wallpaperEngine != "awww") ''
      # Not the awww engine — hyprpaper owns the wallpaper and cannot change it
      # at runtime, so there is nothing to do.
      exit 0
    ''}

    # The daemon is started from exec-once alongside us, so at login we can win
    # the race. Wait briefly rather than silently leaving the desktop bare.
    for _ in $(seq 1 40); do
      ${pkgs.awww}/bin/awww query >/dev/null 2>&1 && break
      ${pkgs.coreutils}/bin/sleep 0.25
    done
    ${pkgs.awww}/bin/awww query >/dev/null 2>&1 || exit 0

    # awww -o takes OUTPUT NAMES (DP-1, HDMI-A-1). hyprpaper-style identifiers
    # may instead be `desc:<description>`, which only Hyprland can resolve — and
    # it is a PREFIX match, because Hyprland appends a serial to .description.
    resolve() {
      case "$1" in
        "") ${pkgs.hyprland}/bin/hyprctl -j monitors 2>/dev/null \
              | ${pkgs.jq}/bin/jq -r '.[].name' | ${pkgs.coreutils}/bin/paste -sd, ;;
        desc:*) ${pkgs.hyprland}/bin/hyprctl -j monitors 2>/dev/null \
              | ${pkgs.jq}/bin/jq -r --arg d "''${1#desc:}" \
                  '.[] | select(.description | startswith($d)) | .name' \
              | ${pkgs.coreutils}/bin/paste -sd, ;;
        *) echo "$1" ;;
      esac
    }

    warned=0
    try_set() {   # $1 identifier, $2 day path, $3 night path
      if [ "$SIDE" = night ]; then IMG="$3"; else IMG="$2"; fi
      if [ ! -f "$IMG" ]; then
        # Missing asset: keep the day image rather than blanking the desktop.
        if [ "$warned" = 0 ]; then
          ${pkgs.libnotify}/bin/notify-send -t 4000 -i image \
            "Night mode" "Wallpaper missing, keeping the day image" 2>/dev/null || true
          warned=1
        fi
        IMG="$2"
        [ -f "$IMG" ] || return 0
      fi
      OUT=$(resolve "$1")
      [ -z "$OUT" ] && return 0
      if [ "$DUR" = 0 ]; then
        ${pkgs.awww}/bin/awww img -o "$OUT" "$IMG" --resize crop -t none >/dev/null 2>&1 || true
      else
        # .4,0,.2,1 is the theme's own `hydraulic` bezier from hyprland.nix, so
        # the wallpaper fade shares a motion curve with the window animations.
        ${pkgs.awww}/bin/awww img -o "$OUT" "$IMG" --resize crop \
          -t fade --transition-duration "$DUR" --transition-fps 60 \
          --transition-bezier .4,0,.2,1 >/dev/null 2>&1 || true
      fi
    }

    ${wallpaperLines}
  '';

  # ---- shared shell fragments ---------------------------------------------
  readState = ''
    STATE_FILE="${stateFile}"
    PHASE_FILE="${phaseFile}"
    TARGET_FILE="${targetFile}"
    LAST=${toString lastStep}

    ${pkgs.coreutils}/bin/mkdir -p "$(dirname "$STATE_FILE")" "$(dirname "${paletteLive}")"
    [ ! -f "$STATE_FILE" ] && echo "${cfg.mode}" > "$STATE_FILE"
    MODE=$(cat "$STATE_FILE" 2>/dev/null || echo auto)
    case "$MODE" in auto|day|night) ;; *) MODE=auto ;; esac
  '';

  # Target step for the current mode. auto consults the shared solar predicate.
  computeTarget = ''
    if [ "$MODE" = day ]; then
      TARGET=0
    elif [ "$MODE" = night ]; then
      TARGET=$LAST
    elif [ "$(${isDay})" = "1" ]; then
      TARGET=0
    else
      TARGET=$LAST
    fi
  '';

  scheduleScript = pkgs.writeShellScriptBin "century-night-schedule" ''
    set -u
    [ "''${XDG_CURRENT_DESKTOP:-}" != "Hyprland" ] && exit 0
    ${readState}
    ${computeTarget}

    APPLIED=$(cat "$PHASE_FILE" 2>/dev/null || echo "")

    if [ "$APPLIED" = "$TARGET" ]; then
      # Re-assert even though nothing changed. `hyprctl keyword` values do not
      # survive `hyprctl reload`, which happens on every rebuild, while the
      # phase file still says night — without this the compositor sits on day
      # borders until the next real boundary, hours later. ~30ms.
      #
      # Reload waybar ONLY if the palette actually changed, i.e. a rebuild
      # altered the colours under a live session. Reloading unconditionally
      # here would restart both bars every 5 minutes.
      BEFORE=$(${pkgs.coreutils}/bin/cksum "${paletteLive}" 2>/dev/null || echo none)
      ${applyStep} "$TARGET" || true
      AFTER=$(${pkgs.coreutils}/bin/cksum "${paletteLive}" 2>/dev/null || echo none)
      [ "$BEFORE" != "$AFTER" ] && ${reloadWaybar}
      exit 0
    fi

    # A walk toward this same target is already in flight — let it finish
    # rather than restarting it from the top on every poll.
    if [ "$(cat "$TARGET_FILE" 2>/dev/null)" = "$TARGET" ] \
       && ${systemctl} --user is-active --quiet century-night-ramp.service; then
      exit 0
    fi

    echo "$TARGET" > "$TARGET_FILE"
    ${systemctl} --user restart --no-block century-night-ramp.service
  '';

  rampScript = pkgs.writeShellScriptBin "century-night-ramp" ''
    set -u
    [ "''${XDG_CURRENT_DESKTOP:-}" != "Hyprland" ] && exit 0
    ${readState}

    TARGET=$(cat "$TARGET_FILE" 2>/dev/null || echo "")
    [ -z "$TARGET" ] && exit 0
    # Unknown phase: assume we are at the opposite end so the walk is visible.
    CUR=$(cat "$PHASE_FILE" 2>/dev/null || echo "")
    if [ -z "$CUR" ]; then CUR=$(( LAST - TARGET )); fi
    [ "$CUR" = "$TARGET" ] && exit 0

    if [ "$TARGET" -gt "$CUR" ]; then DIR=1; N=$(( TARGET - CUR )); else DIR=-1; N=$(( CUR - TARGET )); fi
    INTERVAL=$(${pkgs.gawk}/bin/awk -v t=${toString cfg.transitionSeconds} -v n="$N" \
      'BEGIN { printf "%.3f", (n > 0 ? t / n : 0) }')
    MID=$(( (CUR + TARGET) / 2 ))
    RELOADED=0

    # Fire the wallpaper crossfade ONCE, up front: awww animates it itself over
    # the same wall-clock duration, so it runs alongside the compositor walk.
    if [ "$TARGET" = 0 ]; then SIDE=day; else SIDE=night; fi
    ${wallpaperScript}/bin/century-wallpaper-apply "$SIDE" ${toString cfg.transitionSeconds} || true

    i=$CUR
    while [ "$i" != "$TARGET" ]; do
      i=$(( i + DIR ))
      # Compositor only: the interpolated part, every step.
      ${applyStep} "$i" live || true
      echo "$i" > "$PHASE_FILE"

      # Waybar crosses over ONCE, halfway through, straight to the target
      # palette — a reload per step is what made both bars vanish. Doing it at
      # the midpoint rather than at the end keeps it inside the compositor fade
      # so the whole thing still reads as one event.
      if [ "$i" = "$MID" ] && [ "$RELOADED" = 0 ]; then
        ${applyStep} "$TARGET" files || true
        ${reloadWaybar}
        RELOADED=1
      fi

      if [ "$i" != "$TARGET" ]; then ${pkgs.coreutils}/bin/sleep "$INTERVAL"; fi
    done

    # A one-step ramp never passes its own midpoint, so make the single
    # crossover unconditional. The palette write is idempotent, so when the
    # midpoint already did it this only settles the file.
    ${applyStep} "$TARGET" files || true
    [ "$RELOADED" = 0 ] && ${reloadWaybar}
    exit 0
  '';

  # On PATH via home.packages, matching hyprsunset-init: ~/.local/bin is NOT on
  # PATH here, so a script dropped there is reachable only by absolute path.
  cliScript = pkgs.writeShellScriptBin "century-night" ''
    set -u
    ${readState}

    stop_ramp() { ${systemctl} --user stop century-night-ramp.service 2>/dev/null || true; }

    # Apply a step with no animation and tell waybar. This is the fallback
    # whenever systemd cannot be reached (units not activated yet, no user
    # bus), so that no subcommand is ever a silent no-op.
    apply_now() {
      ${applyStep} "$1" || true
      echo "$1" > "$PHASE_FILE"
      echo "$1" > "$TARGET_FILE"
      if [ "$1" = 0 ]; then SIDE=day; else SIDE=night; fi
      ${wallpaperScript}/bin/century-wallpaper-apply "$SIDE" 0 || true
      ${reloadWaybar}
    }

    pin() {   # $1 = day|night, ramp toward it
      echo "$1" > "$STATE_FILE"
      MODE="$1"
      ${computeTarget}
      stop_ramp
      echo "$TARGET" > "$TARGET_FILE"
      if ! ${systemctl} --user restart --no-block century-night-ramp.service 2>/dev/null; then
        apply_now "$TARGET"
      fi
    }

    case "''${1:-status}" in
      init)
        # Instant, no ramp: login and home-manager activation. Safe with no
        # compositor — the step script writes files and skips every hyprctl.
        ${computeTarget}
        apply_now "$TARGET"
        ;;
      now)
        case "''${2:-}" in
          day) T=0 ;; night) T=$LAST ;;
          *) echo "usage: century-night now day|night" >&2; exit 1 ;;
        esac
        echo "''${2}" > "$STATE_FILE"
        stop_ramp
        apply_now "$T"
        ;;
      day)   pin day ;;
      night) pin night ;;
      auto)
        echo auto > "$STATE_FILE"
        MODE=auto
        stop_ramp
        if ! ${systemctl} --user start --no-block century-night-schedule.service 2>/dev/null; then
          ${computeTarget}
          apply_now "$TARGET"
        fi
        ;;
      toggle)
        P=$(cat "$PHASE_FILE" 2>/dev/null || echo 0)
        if [ "$P" -ge $(( LAST / 2 + 1 )) ]; then pin day; else pin night; fi
        ;;
      reconcile)
        if ! ${systemctl} --user start --no-block century-night-schedule.service 2>/dev/null; then
          ${computeTarget}
          apply_now "$TARGET"
        fi
        ;;
      status)
        P=$(cat "$PHASE_FILE" 2>/dev/null || echo "?")
        D=$(${isDay} 2>/dev/null || echo "?")
        if ${systemctl} --user is-active --quiet century-night-ramp.service 2>/dev/null; then R=ramping; else R=idle; fi
        [ "$D" = 1 ] && SUN=day || SUN=night
        echo "mode=$MODE phase=$P/$LAST sun=$SUN $R"
        ;;
      *)
        echo "usage: century-night {status|init|day|night|auto|toggle|reconcile|now day|now night}" >&2
        exit 1
        ;;
    esac
  '';

in {
  config = mkIf enabled {
    home.packages = [ scheduleScript rampScript cliScript wallpaperScript ];

    # The waybar stylesheet @imports this file by absolute path, and a MISSING
    # import makes GTK reject the entire provider — unstyled bars. So it must
    # exist before waybar ever starts, and it must be refreshed on every
    # rebuild: the store palette may have changed while the live copy did not.
    #
    # This deliberately does not signal waybar. A rebuild inside a live session
    # leaves the bar on the old colours for up to 5 minutes, and then the
    # reconciler notices the palette checksum moved and reloads it once. Doing
    # it here as well would mean two reloads for one rebuild.
    home.activation.centuryNightPalette = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if [ -L "${paletteLive}" ]; then
        $DRY_RUN_CMD rm -f "${paletteLive}"
      fi
      $DRY_RUN_CMD ${pkgs.coreutils}/bin/mkdir -p "$(dirname "${paletteLive}")" "${homeDir}/.cache"
      PHASE=$(cat "${phaseFile}" 2>/dev/null || echo 0)
      case "$PHASE" in ""|*[!0-9]*) PHASE=0 ;; esac
      [ "$PHASE" -gt ${toString lastStep} ] && PHASE=${toString lastStep}
      $DRY_RUN_CMD ${applyStep} "$PHASE" || true
    '';

    systemd.user.services.century-night-schedule = {
      Unit.Description = "Reconcile the century-series day/night palette with the time of day";
      Service = {
        Type = "oneshot";
        ExecStart = "${scheduleScript}/bin/century-night-schedule";
      };
    };

    systemd.user.services.century-night-ramp = {
      Unit.Description = "Animated century-series day/night palette transition";
      # Foreground walk: `systemctl --user restart` retargets it and `stop`
      # cancels it. It backgrounds nothing, so the default KillMode is correct.
      Service.ExecStart = "${rampScript}/bin/century-night-ramp";
    };

    systemd.user.timers.century-night-schedule = {
      Unit.Description = "Century-series day/night reconcile timer";
      Timer = {
        # Poll rather than fire at the boundary: it moves with the sun, and a
        # poll also recovers from suspend, a crash, a rebuild's hyprctl reload,
        # and a mode change.
        OnCalendar = [ "*:0/5" ];
        AccuracySec = "30s";
        Persistent = true;
      };
      Install.WantedBy = [ "timers.target" ];
    };
  };
}
