# ~/nixos-config/modules/home-manager/themes/century-series/night-mode.nix
#
# century-night: swaps the century-series theme between its DAY palette and its
# NIGHT (F-117/B-2 stealth cockpit) palette, animated, on the same sunset
# boundary hyprsunset uses.
#
#   century-night init       apply the right palette instantly (login, activation)
#   century-night status     MODE, phase, and which side of the boundary we are on
#   century-night day|night  pin a palette and ramp to it
#   century-night auto       follow the sun again
#   century-night toggle     flip to the other side (pins a manual mode)
#   century-night reconcile  run the reconciler now
#
# Structure is deliberately a copy of scripts/hyprsunset-control.nix, because
# that module already solved this problem shape:
#   century-night-schedule.service  oneshot reconciler, run every 5 min by its
#     timer. Works out the target from hyprsunset-isday and hands a GRADUAL
#     transition to the ramp whenever the applied phase does not match. Polling
#     rather than firing at the boundary is what makes it self-healing: it also
#     catches resume-from-suspend, a crash, and a mode change.
#   century-night-ramp.service      the walk itself, in the FOREGROUND so
#     systemd owns its lifecycle — `restart` retargets, `stop` cancels. Unlike
#     hyprsunset-transition this backgrounds nothing, so it keeps the default
#     KillMode and avoids that module's orphaned-`sleep` wart.
#
# State (~/.cache/), kept INDEPENDENT of hyprsunset's: its reconciler exits
# early when its own mode is manual/disabled, so piggybacking on it would mean
# the theme silently stopped switching the moment someone scrolled that widget.
#   century-night-state   MODE: auto | day | night
#   century-night-phase   step index currently applied (0 = day, N = night)
#   century-night-target  step index the ramp is walking to
#   century-night-shader  path of the current-phase CRT shader, read by
#                         century-crt-toggle so the opt-in filter matches
#
# The boundary itself is NOT reimplemented here: hyprsunset-solar.nix is the
# single source of truth (its header records that this arithmetic was once
# copy-pasted into five scripts). It is referenced by absolute store path, not
# $PATH, because that binary is only in home.packages when hyprsunset is
# enabled — and night mode must work when it is not.
{ config, pkgs, lib, customConfig, ... }:

with lib;

let
  colorsModule = import ./colors.nix { };
  crtShaders = import ./crt-shader.nix { };

  cfg = customConfig.homeManager.themes.centurySeries.night;
  sunCfg = customConfig.homeManager.services.hyprsunset;

  centurySeriesThemeCondition = lib.elem "hyprland" customConfig.desktop.environments
    && customConfig.homeManager.themes.hyprland == "century-series";
  enabled = centurySeriesThemeCondition && cfg.enable;

  # N steps => N+1 palettes, endpoints exact (see colors.nix).
  steps = cfg.steps;
  palettes = colorsModule.paletteSteps steps;
  lastStep = steps;

  isDay = "${import ../../scripts/hyprsunset-solar.nix {
    inherit pkgs;
    cfg = sunCfg;
  }}/bin/hyprsunset-isday";

  systemctl = "${pkgs.systemd}/bin/systemctl";
  hyprctl = "${pkgs.hyprland}/bin/hyprctl";

  homeDir = config.home.homeDirectory;
  paletteLive = "${homeDir}/.config/waybar/century-palette.css";
  stateFile = "${homeDir}/.cache/century-night-state";
  phaseFile = "${homeDir}/.cache/century-night-phase";
  targetFile = "${homeDir}/.cache/century-night-target";
  shaderFile = "${homeDir}/.cache/century-night-shader";
  # Runtime dir, not ~/.cache: this warning is per-session, and a fresh session
  # is exactly what clears the condition.
  wallpaperWarnFile = "\${XDG_RUNTIME_DIR:-/tmp}/century-night-wallpaper-warned";

  # ---- generated artifacts -------------------------------------------------
  # GTK named colours. @define-color takes #rrggbb or rgba() but REJECTS
  # 8-digit hex, so anything carrying alpha is emitted as rgba().
  cssName = n: "c_" + builtins.replaceStrings [ "-" ] [ "_" ] n;
  defineColor = n: hex:
    let v = colorsModule.rgbaOf hex;
    in if v.a >= 1.0
       then "@define-color ${cssName n} ${builtins.substring 0 7 hex};"
       else "@define-color ${cssName n} rgba(${toString v.r}, ${toString v.g}, ${toString v.b}, ${toString v.a});";

  mkPaletteCss = pal: ''
    /* century-series palette — GENERATED by night-mode.nix, rewritten on every
       ramp step. Do not edit: your changes will be overwritten within 5
       minutes. Edit colors.nix instead. */
  '' + concatStringsSep "\n" (mapAttrsToList defineColor pal) + "\n";

  lerpF = a: b: t: a + (b - a) * t;
  tAt = i: i * 1.0 / (lastStep * 1.0);
  # Night is dimmer, not just redder.
  dimAt = i: lerpF 0.15 0.30 (tAt i);
  brightAt = i: lerpF 0.95 0.80 (tAt i);
  blueAttenAt = i: lerpF 1.0 0.55 (tAt i);

  sh = s: removePrefix "#" s;

  mkStep = i:
    let
      p = elemAt palettes i;
      css = pkgs.writeText "century-palette-${toString i}.css" (mkPaletteCss p);
      shader = pkgs.writeText "century-crt-${toString i}.glsl"
        (crtShaders.mkCrtBarrelShader p (blueAttenAt i));
    in pkgs.writeShellScript "century-night-step-${toString i}" ''
      set -u
      # $1 selects which half to apply:
      #   all   (default) files + compositor — login, activation, re-assert
      #   files palette + shader pointer only
      #   live  compositor keywords only — what each ramp step uses
      # The split exists because waybar can only be restyled by a reload, and a
      # reload cannot happen once per step (see the ramp script).
      STEP_MODE="''${1:-all}"

      if [ "$STEP_MODE" != live ]; then
        # Only write when the content actually differs. The 5-minute reconciler
        # re-asserts the current step even when nothing changed, and an
        # unconditional write would bump the mtime every 5 minutes forever.
        #
        # Atomic rename, never an in-place write: GTK must not see a truncated
        # palette, and ANY parse error rejects the whole provider (unstyled bars).
        if ! ${pkgs.diffutils}/bin/cmp -s ${css} "${paletteLive}"; then
          ${pkgs.coreutils}/bin/install -m644 ${css} "${paletteLive}.new"
          ${pkgs.coreutils}/bin/mv -f "${paletteLive}.new" "${paletteLive}"
        fi

        echo "${shader}" > "${shaderFile}"

        # Per-app colour files for this side of the boundary. These apps cannot
        # interpolate, so they flip once, at the halfway step, rather than
        # following the ramp — which is also when waybar crosses over, so the
        # whole non-interpolatable half of the theme changes together.
        ${appThemeScript}/bin/century-apps-apply ${
          if i * 2 >= lastStep then "night" else "day"
        } || true
      fi

      [ "$STEP_MODE" = files ] && exit 0

      # Everything below needs a live compositor, and hyprctl needs
      # HYPRLAND_INSTANCE_SIGNATURE — which is NOT in the systemd user
      # environment: hyprland/functional.nix imports only WAYLAND_DISPLAY,
      # DISPLAY, XDG_CURRENT_DESKTOP and XDG_MENU_PREFIX via
      # dbus-update-activation-environment. Without this discovery the ramp
      # would run from its service, repaint the bar, and silently never touch a
      # single border. Same approach as the claude-rwr widget in waybar.nix.
      if [ -z "''${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
        export XDG_RUNTIME_DIR="''${XDG_RUNTIME_DIR:-/run/user/$(${pkgs.coreutils}/bin/id -u)}"
        shopt -s nullglob
        for entry in "$XDG_RUNTIME_DIR"/hypr/*; do
          name="$(${pkgs.coreutils}/bin/basename "$entry")"
          case "$name" in *.lock) continue ;; esac
          if [ -d "$entry" ]; then export HYPRLAND_INSTANCE_SIGNATURE="$name"; break; fi
        done
        shopt -u nullglob
      fi
      [ -z "''${HYPRLAND_INSTANCE_SIGNATURE:-}" ] && exit 0

      # One batch so all four land in the same frame. NOTE: deliberately NOT
      # ramping `windowrule border_color` — `hyprctl keyword windowrule`
      # APPENDS rather than replaces, so ramping it would leak ~48 dead rules
      # into the rule list every day.
      ${hyprctl} --batch "\
        keyword general:col.inactive_border rgb(${sh p.border-primary}) ; \
        keyword general:col.active_border rgb(${sh p.accent-amber}) rgb(${sh p.border-active}) 45deg ; \
        keyword decoration:dim_strength ${toString (dimAt i)} ; \
        keyword decoration:blur:brightness ${toString (brightAt i)}" >/dev/null 2>&1 || true

      # Restyle the CRT filter only when it is already on (it is opt-in).
      # A DIFFERENT path per step is required: Hyprland caches the compiled
      # shader by path, so rewriting one file in place would not recompile.
      CUR=$(${hyprctl} getoption decoration:screen_shader 2>/dev/null \
            | ${pkgs.gnugrep}/bin/grep "str:" | ${pkgs.gawk}/bin/awk '{print $2}')
      if [ -n "$CUR" ] && [ "$CUR" != "[[EMPTY]]" ]; then
        ${hyprctl} keyword decoration:screen_shader "${shader}" >/dev/null 2>&1 || true
      fi
    '';

  stepScripts = genList mkStep (steps + 1);

  # usage: apply-step <index> [all|files|live]
  applyStep = pkgs.writeShellScript "century-night-apply-step" ''
    case "$1" in
    ${concatStringsSep "\n    " (imap0 (i: s: "${toString i}) exec ${s} \"\${2:-all}\" ;;") stepScripts)}
      *) echo "century-night: no such step: $1" >&2; exit 1 ;;
    esac
  '';

  # Restyle waybar. SIGUSR2 is the ONLY thing that works here, and it must be
  # used sparingly:
  #   * `reload_style_on_change` does NOT fire for @imported files — verified in
  #     a live session, both for an atomic rename and an in-place append. The
  #     top-level stylesheet is an immutable store symlink, so it never changes
  #     either, which makes that option useless for this and it is not set.
  #   * SIGUSR2 is a full reload that recreates the bars. ONE is clean; eleven
  #     in a row (one per ramp step) made both bars disappear entirely.
  #   * SIGUSR2 is unusable once waybar-start runs TWO bars (main + launcher),
  #     which it does whenever the launcher is enabled. A reload makes the
  #     second process take GApplication's D-Bus "remote" path — both share one
  #     application id — and GLib aborts it:
  #       GLib-GIO:ERROR:gapplicationimpl-dbus.c:851:
  #       g_application_impl_command_line: assertion failed: (object_id != 0)
  #     Staggering the signals does NOT help; it is structural, not a race. The
  #     launcher bar dies and leaves a zombie, which is easy to miss because
  #     `pgrep -c waybar` still counts it.
  # So the bar is RESTARTED instead, once per transition, at the midpoint of the
  # ramp while the compositor colours keep interpolating around it. That costs a
  # sub-second blink and is correct whether one bar is running or two.
  #
  # Via waybar-start, not a bare `waybar`: the wrapper is what splits the config
  # and honours the launchbar-hidden state. setsid so it outlives this script,
  # which runs inside the ramp service. No -x on pkill: NixOS wraps the binary
  # as `.waybar-wrapped`.
  # Matching on `waybar --config` rather than plain `waybar` is load-bearing:
  # a bare `pkill waybar` also matches the waybar-start WRAPPER, whose comm is
  # `waybar-start`. Kill it in the window after it has backgrounded the launcher
  # bar but before it execs the main one and you get a launcher with no main
  # bar — which is exactly what happened. Only the real bars carry
  # `waybar --config <path>` in their argv, so -f on that is precise.
  reloadWaybar = pkgs.writeShellScript "century-night-reload-waybar" ''
    ${pkgs.procps}/bin/pkill -f 'waybar --config' 2>/dev/null || true
    ${pkgs.coreutils}/bin/sleep 0.5
    ${pkgs.util-linux}/bin/setsid "$HOME/.local/bin/waybar-start" \
      > "''${XDG_RUNTIME_DIR:-/tmp}/waybar-start.log" 2>&1 &
  '';

  # Refresh the custom/century-night widget. SEPARATE from reloadWaybar: that
  # one is SIGUSR2, a full reload of both bars, and is only safe once per
  # transition. This is the per-widget poke the widget subscribes to via
  # `signal = 17`. An unhandled realtime signal TERMINATES the target, so this
  # must never be sent unless that widget is configured. No -x: NixOS wraps it.
  # Matched on `waybar --config` for the same reason as reloadWaybar, and here
  # it matters even more: a bare `pkill waybar` also hits the waybar-start
  # WRAPPER, which has no handler for RTMIN+17, and an unhandled realtime signal
  # TERMINATES its target. Catch the wrapper between backgrounding the launcher
  # and exec'ing the main bar and you lose the main bar entirely.
  pokeWidget = "${pkgs.procps}/bin/pkill -RTMIN+17 -f 'waybar --config' 2>/dev/null || true";

  # ---- per-application colour files ---------------------------------------
  # Apps that read their config only at launch — or, like kitty, can be poked
  # into re-reading it. Each entry generates a day and a night file in the
  # store; the live path is a writable real file the switcher installs over and
  # home.activation seeds, the same shape as the waybar palette.
  #
  # Adding an app is one entry here plus a generator in app-themes.nix.
  appThemes = import ./app-themes.nix { inherit lib; };

  swappable = [
    {
      name = "kitty";
      live = "${homeDir}/.config/kitty/century-colors.conf";
      mk = appThemes.mkKittyColors;
      # SIGUSR1 makes kitty re-read its config in place, so terminals that are
      # already open change colour without a restart. No -x: NixOS wraps it.
      reload = "${pkgs.procps}/bin/pkill -SIGUSR1 kitty 2>/dev/null || true";
    }
    {
      name = "starship";
      live = "${homeDir}/.config/starship.toml";
      mk = appThemes.mkStarshipToml;
      # starship re-reads the file per prompt, so the next prompt in any open
      # shell is already the new palette. Nothing to signal.
      reload = "true";
    }
    # The rest read their config once, at launch: anything already open keeps
    # the old palette until it is reopened. None of them has a reload hook.
    {
      name = "btop";
      live = "${homeDir}/.config/btop/themes/century-series.theme";
      mk = appThemes.mkBtopTheme;
      reload = "true";
    }
    {
      name = "yazi";
      live = "${homeDir}/.config/yazi/theme.toml";
      mk = appThemes.mkYaziTheme;
      reload = "true";
    }
    {
      name = "imv";
      live = "${homeDir}/.config/imv/config";
      mk = appThemes.mkImvConfig;
      reload = "true";
    }
    {
      name = "zathura";
      live = "${homeDir}/.config/zathura/century-colors";
      mk = appThemes.mkZathuraColors;
      reload = "true";
    }
    {
      name = "swaylock";
      live = "${homeDir}/.config/swaylock/config";
      # Reproduces home-manager's own renderer exactly (see its swaylock.nix):
      # a bare key for true, key=value otherwise, and false omitted entirely.
      mk = p: concatStrings (mapAttrsToList (n: v:
        if v == false then ""
        else (if v == true then n else "${n}=${toString v}") + "\n"
      ) (appThemes.mkSwaylockSettings p));
      reload = "true";
    }
    {
      name = "rofi";
      live = "${homeDir}/.config/rofi/century-colors.rasi";
      mk = appThemes.mkRofiColors;
      reload = "true";
    }
    {
      name = "wlogout-css";
      live = "${homeDir}/.config/wlogout/century-colors.css";
      mk = appThemes.mkWlogoutColors;
      reload = "true";
    }
    {
      # Firefox/LibreWolf userChrome. Written unconditionally: the browser
      # module only @imports it when chromeTheme is century-series, and an
      # unreferenced file costs nothing — whereas gating on that option here
      # would couple the theme to the browser preset.
      name = "browser-chrome";
      live = "${homeDir}/.config/century/browser-chrome-colors.css";
      mk = appThemes.mkBrowserChromeColors;
      # Needs a browser restart; Firefox reads userChrome only at startup.
      reload = "true";
    }
  ]
  # wlogout's annunciator tiles bake their colour into the SVG, so the night
  # variant is a different file rather than a restyle. Filenames stay
  # colour-named because the stylesheet references them by name; only the
  # contents change. Two files per tile (normal + hover).
  ++ concatMap (ic: [
    {
      name = "wlogout-${ic.file}";
      live = "${homeDir}/.config/wlogout/icons/${ic.file}.svg";
      mk = p: appThemes.mkSwitchSvg {
        color = p.${ic.key}; label = ic.label; tile = p.wlogout-tile;
      };
      reload = "true";
    }
    {
      name = "wlogout-${ic.file}-hover";
      live = "${homeDir}/.config/wlogout/icons/${ic.file}-hover.svg";
      mk = p: appThemes.mkSwitchHoverSvg { color = p.${ic.key}; label = ic.label; };
      reload = "true";
    }
  ]) appThemes.wlogoutIcons;

  paletteFor = side:
    if side == "night" then colorsModule.centuryNightColors else colorsModule.centuryColors;

  mkAppFile = side: e: pkgs.writeText "century-${e.name}-${side}" (e.mk (paletteFor side));

  # dunst needs no file swap at all: `dunstctl reload <path>` takes a config
  # path, so both variants stay immutable in the store and night mode just
  # points the running daemon at the other one.
  #
  # The night file is the DAY file with its colours substituted, rather than a
  # second render of the settings attrset. Re-rendering looked cleaner but drops
  # what home-manager adds on its way out — notably the computed `icon_path`,
  # without which night notifications lose their icons — and writes true/false
  # where home-manager writes yes/no. Substituting leaves every one of those
  # bytes alone.
  #
  # Only these keys are substituted, because only these appear in
  # mkDunstSettings. That matters: several palette values are shared (#7fda89 is
  # both accent-green and term-fg, which have DIFFERENT night values), so a
  # blanket hex replacement would be ambiguous. Keep this list in step with
  # app-themes.nix if dunst starts using another colour.
  dunstColourKeys = [
    "accent-amber" "accent-amber-dim" "accent-green" "accent-green-dim"
    "bg-primary" "bg-secondary" "caution-yellow" "info-blue" "warning-red"
  ];

  dunstDayRc = config.xdg.configFile."dunst/dunstrc".source;

  dunstNightRc = pkgs.runCommand "century-dunstrc-night" { } ''
    ${pkgs.gnused}/bin/sed ${
      concatMapStringsSep " " (k:
        "-e 's/${colorsModule.centuryColors.${k}}/${colorsModule.centuryNightColors.${k}}/gI'"
      ) dunstColourKeys
    } ${dunstDayRc} > $out
  '';

  # ---- ckb-next keyboard ---------------------------------------------------
  # Index 2 of the existing cycle is already RED, so night mode only SELECTS it
  # and remembers what was there before. The four cycle constants stay in
  # ckb-scripts.nix, which is contracted to match
  # modules/nixos/hardware/peripherals.nix — redefining them here would be a
  # second place to keep in step for no gain.
  #
  # This writes the same state file SUPER+CTRL+K writes, so a manual choice
  # during the night simply sticks until the next boundary. That is the agreed
  # behaviour, not a race.
  ckbScripts = import ./ckb-scripts.nix { inherit pkgs; };
  hasCkbNight = customConfig.hardware.peripherals.ckb-next.enable && cfg.keyboard;

  ckbApply = side: optionalString hasCkbNight ''
    CKB_STATE="${homeDir}/.cache/ckb-color-state"
    CKB_SAVED="${homeDir}/.cache/century-night-ckb-saved"
    if [ -f "$CKB_STATE" ]; then
      CKB_CUR=$(cat "$CKB_STATE" 2>/dev/null || echo "0:80")
      CKB_IDX="''${CKB_CUR%%:*}"
      CKB_BRIGHT="''${CKB_CUR##*:}"
      case "$CKB_BRIGHT" in ""|*[!0-9]*) CKB_BRIGHT=80 ;; esac
    ${if side == "night" then ''
      # Record the day colour only on the FIRST crossing, or the 5-minute
      # re-assert would eventually save RED as the thing to restore.
      [ ! -f "$CKB_SAVED" ] && echo "$CKB_IDX" > "$CKB_SAVED"
      CKB_WANT=2
    '' else ''
      CKB_WANT=$(cat "$CKB_SAVED" 2>/dev/null || echo "$CKB_IDX")
      case "$CKB_WANT" in ""|*[!0-3]*) CKB_WANT=0 ;; esac
      ${pkgs.coreutils}/bin/rm -f "$CKB_SAVED"
    ''}
      if [ "$CKB_IDX" != "$CKB_WANT" ]; then
        echo "$CKB_WANT:$CKB_BRIGHT" > "$CKB_STATE"
        ${ckbScripts.applyCurrentScript}
        ${pkgs.procps}/bin/pkill -RTMIN+14 waybar 2>/dev/null || true
      fi
    fi
  '';

  dunstApply = side: ''
    ${pkgs.dunst}/bin/dunstctl reload ${
      if side == "night" then dunstNightRc else dunstDayRc
    } 2>/dev/null || true
  '';

  # install+mv is atomic, and the cmp guard stops the 5-minute reconciler from
  # rewriting — and reloading — files that have not actually changed.
  appApplyLines = side: concatStringsSep "\n" (map (e: ''
    ${pkgs.coreutils}/bin/mkdir -p "$(${pkgs.coreutils}/bin/dirname ${escapeShellArg e.live})"
    if ! ${pkgs.diffutils}/bin/cmp -s ${mkAppFile side e} ${escapeShellArg e.live}; then
      ${pkgs.coreutils}/bin/install -m644 ${mkAppFile side e} ${escapeShellArg (e.live + ".new")}
      ${pkgs.coreutils}/bin/mv -f ${escapeShellArg (e.live + ".new")} ${escapeShellArg e.live}
      ${e.reload}
    fi
  '') swappable) + "\n" + dunstApply side + "\n" + ckbApply side;

  appThemeScript = pkgs.writeShellScriptBin "century-apps-apply" ''
    set -u
    case "''${1:-day}" in
      day)   ${appApplyLines "day"} ;;
      night) ${appApplyLines "night"} ;;
      *) echo "usage: century-apps-apply day|night" >&2; exit 1 ;;
    esac
  '';

  # ---- wallpaper ----------------------------------------------------------
  # usage: century-wallpaper-apply <day|night> <fade-seconds>
  #
  # One call per transition, fired up front by the ramp: awww runs its own GPU
  # crossfade over the same duration, so the wallpaper fade and the compositor
  # walk overlap instead of queueing. K calls would fight each other.
  wallpaperSets = import ./wallpapers.nix {
    inherit lib customConfig;
    homeDir = homeDir;
  };

  # Day and night assignment lists are parallel — same monitors, same order —
  # so they zip into one try_set line per display.
  wallpaperLines = concatStringsSep "\n" (imap0 (i: d:
    let n = elemAt wallpaperSets.nightAssignments i;
    in ''try_set "${d.monitor}" "${d.path}" "${n.path}"''
  ) wallpaperSets.dayAssignments);

  wallpaperScript = pkgs.writeShellScriptBin "century-wallpaper-apply" ''
    set -u
    SIDE="''${1:-day}"
    DUR="''${2:-0}"
    [ "''${XDG_CURRENT_DESKTOP:-}" != "Hyprland" ] && exit 0
    ${lib.optionalString (customConfig.desktop.hyprland.wallpaperEngine != "awww") ''
      # Not the awww engine — hyprpaper owns the wallpaper and cannot change it
      # at runtime, so there is nothing to do.
      exit 0
    ''}

    # The daemon is started from exec-once alongside us, so at login we can win
    # the race. Wait briefly rather than silently leaving the desktop bare.
    for _ in $(seq 1 40); do
      ${pkgs.awww}/bin/awww query >/dev/null 2>&1 && break
      ${pkgs.coreutils}/bin/sleep 0.25
    done
    if ! ${pkgs.awww}/bin/awww query >/dev/null 2>&1; then
      # Almost always one specific thing: the session predates the rebuild that
      # switched wallpaperEngine to awww. exec-once only runs at session start,
      # so hyprpaper is still up from the old config and awww-daemon was never
      # launched — colours switch (they go through hyprctl) but wallpapers do
      # not. Silence here looks like a broken feature, so say it once per
      # session rather than exiting quietly.
      if [ ! -f "${wallpaperWarnFile}" ]; then
        : > "${wallpaperWarnFile}"
        ${pkgs.libnotify}/bin/notify-send -t 10000 -i preferences-desktop-wallpaper \
          "Night mode" \
          "Wallpapers need a fresh Hyprland session: awww-daemon is not running (hyprpaper probably still is, from before the last rebuild)." 2>/dev/null || true
      fi
      exit 0
    fi

    # awww -o takes OUTPUT NAMES (DP-1, HDMI-A-1). hyprpaper-style identifiers
    # may instead be `desc:<description>`, which only Hyprland can resolve — and
    # it is a PREFIX match, because Hyprland appends a serial to .description.
    resolve() {
      case "$1" in
        "") ${pkgs.hyprland}/bin/hyprctl -j monitors 2>/dev/null \
              | ${pkgs.jq}/bin/jq -r '.[].name' | ${pkgs.coreutils}/bin/paste -sd, ;;
        desc:*) ${pkgs.hyprland}/bin/hyprctl -j monitors 2>/dev/null \
              | ${pkgs.jq}/bin/jq -r --arg d "''${1#desc:}" \
                  '.[] | select(.description | startswith($d)) | .name' \
              | ${pkgs.coreutils}/bin/paste -sd, ;;
        *) echo "$1" ;;
      esac
    }

    warned=0
    try_set() {   # $1 identifier, $2 day path, $3 night path
      if [ "$SIDE" = night ]; then IMG="$3"; else IMG="$2"; fi
      if [ ! -f "$IMG" ]; then
        # Missing asset: keep the day image rather than blanking the desktop.
        if [ "$warned" = 0 ]; then
          ${pkgs.libnotify}/bin/notify-send -t 4000 -i image \
            "Night mode" "Wallpaper missing, keeping the day image" 2>/dev/null || true
          warned=1
        fi
        IMG="$2"
        [ -f "$IMG" ] || return 0
      fi
      OUT=$(resolve "$1")
      [ -z "$OUT" ] && return 0
      if [ "$DUR" = 0 ]; then
        ${pkgs.awww}/bin/awww img -o "$OUT" "$IMG" --resize crop -t none >/dev/null 2>&1 || true
      else
        # .4,0,.2,1 is the theme's own `hydraulic` bezier from hyprland.nix, so
        # the wallpaper fade shares a motion curve with the window animations.
        ${pkgs.awww}/bin/awww img -o "$OUT" "$IMG" --resize crop \
          -t fade --transition-duration "$DUR" --transition-fps 60 \
          --transition-bezier .4,0,.2,1 >/dev/null 2>&1 || true
      fi
    }

    ${wallpaperLines}
  '';

  # ---- shared shell fragments ---------------------------------------------
  readState = ''
    STATE_FILE="${stateFile}"
    PHASE_FILE="${phaseFile}"
    TARGET_FILE="${targetFile}"
    LAST=${toString lastStep}

    ${pkgs.coreutils}/bin/mkdir -p "$(dirname "$STATE_FILE")" "$(dirname "${paletteLive}")"
    [ ! -f "$STATE_FILE" ] && echo "${cfg.mode}" > "$STATE_FILE"
    MODE=$(cat "$STATE_FILE" 2>/dev/null || echo auto)
    case "$MODE" in auto|day|night) ;; *) MODE=auto ;; esac
  '';

  # Target step for the current mode. auto consults the shared solar predicate.
  computeTarget = ''
    if [ "$MODE" = day ]; then
      TARGET=0
    elif [ "$MODE" = night ]; then
      TARGET=$LAST
    elif [ "$(${isDay})" = "1" ]; then
      TARGET=0
    else
      TARGET=$LAST
    fi
  '';

  scheduleScript = pkgs.writeShellScriptBin "century-night-schedule" ''
    set -u
    [ "''${XDG_CURRENT_DESKTOP:-}" != "Hyprland" ] && exit 0
    ${readState}
    ${computeTarget}

    APPLIED=$(cat "$PHASE_FILE" 2>/dev/null || echo "")

    if [ "$APPLIED" = "$TARGET" ]; then
      # Re-assert even though nothing changed. `hyprctl keyword` values do not
      # survive `hyprctl reload`, which happens on every rebuild, while the
      # phase file still says night — without this the compositor sits on day
      # borders until the next real boundary, hours later. ~30ms.
      #
      # Reload waybar ONLY if the palette actually changed, i.e. a rebuild
      # altered the colours under a live session. Reloading unconditionally
      # here would restart both bars every 5 minutes.
      BEFORE=$(${pkgs.coreutils}/bin/cksum "${paletteLive}" 2>/dev/null || echo none)
      ${applyStep} "$TARGET" || true
      AFTER=$(${pkgs.coreutils}/bin/cksum "${paletteLive}" 2>/dev/null || echo none)
      # A restart and a poke are MUTUALLY EXCLUSIVE: a freshly started waybar
      # has not installed its RTMIN+17 handler yet, and an unhandled realtime
      # signal kills it. The restart already brings the bar up on current
      # state, so there is nothing left to poke.
      if [ "$BEFORE" != "$AFTER" ]; then
        ${reloadWaybar}
      else
        ${pokeWidget}
      fi
      exit 0
    fi

    # A walk toward this same target is already in flight — let it finish
    # rather than restarting it from the top on every poll.
    if [ "$(cat "$TARGET_FILE" 2>/dev/null)" = "$TARGET" ] \
       && ${systemctl} --user is-active --quiet century-night-ramp.service; then
      exit 0
    fi

    echo "$TARGET" > "$TARGET_FILE"
    ${systemctl} --user restart --no-block century-night-ramp.service
  '';

  rampScript = pkgs.writeShellScriptBin "century-night-ramp" ''
    set -u
    [ "''${XDG_CURRENT_DESKTOP:-}" != "Hyprland" ] && exit 0
    ${readState}

    TARGET=$(cat "$TARGET_FILE" 2>/dev/null || echo "")
    [ -z "$TARGET" ] && exit 0
    # Unknown phase: assume we are at the opposite end so the walk is visible.
    CUR=$(cat "$PHASE_FILE" 2>/dev/null || echo "")
    if [ -z "$CUR" ]; then CUR=$(( LAST - TARGET )); fi
    [ "$CUR" = "$TARGET" ] && exit 0

    if [ "$TARGET" -gt "$CUR" ]; then DIR=1; N=$(( TARGET - CUR )); else DIR=-1; N=$(( CUR - TARGET )); fi
    INTERVAL=$(${pkgs.gawk}/bin/awk -v t=${toString cfg.transitionSeconds} -v n="$N" \
      'BEGIN { printf "%.3f", (n > 0 ? t / n : 0) }')
    MID=$(( (CUR + TARGET) / 2 ))
    RELOADED=0

    # Fire the wallpaper crossfade ONCE, up front: awww animates it itself over
    # the same wall-clock duration, so it runs alongside the compositor walk.
    if [ "$TARGET" = 0 ]; then SIDE=day; else SIDE=night; fi
    ${wallpaperScript}/bin/century-wallpaper-apply "$SIDE" ${toString cfg.transitionSeconds} || true

    i=$CUR
    while [ "$i" != "$TARGET" ]; do
      i=$(( i + DIR ))
      # Compositor only: the interpolated part, every step.
      ${applyStep} "$i" live || true
      echo "$i" > "$PHASE_FILE"
      # Poke the widget — but NOT on the midpoint step, which restarts the bar
      # just below. A restart and a poke are mutually exclusive: a freshly
      # started waybar has not installed its RTMIN+17 handler yet, and an
      # unhandled realtime signal kills it.
      if [ "$i" != "$MID" ] || [ "$RELOADED" != 0 ]; then
        ${pokeWidget}
      fi

      # Waybar crosses over ONCE, halfway through, straight to the target
      # palette — a reload per step is what made both bars vanish. Doing it at
      # the midpoint rather than at the end keeps it inside the compositor fade
      # so the whole thing still reads as one event.
      if [ "$i" = "$MID" ] && [ "$RELOADED" = 0 ]; then
        ${applyStep} "$TARGET" files || true
        ${reloadWaybar}
        RELOADED=1
      fi

      if [ "$i" != "$TARGET" ]; then ${pkgs.coreutils}/bin/sleep "$INTERVAL"; fi
    done

    # A one-step ramp never passes its own midpoint, so make the single
    # crossover unconditional. The palette write is idempotent, so when the
    # midpoint already did it this only settles the file.
    ${applyStep} "$TARGET" files || true
    if [ "$RELOADED" = 0 ]; then
      ${reloadWaybar}
    else
      ${pokeWidget}
    fi
    exit 0
  '';

  # On PATH via home.packages, matching hyprsunset-init: ~/.local/bin is NOT on
  # PATH here, so a script dropped there is reachable only by absolute path.
  cliScript = pkgs.writeShellScriptBin "century-night" ''
    set -u
    ${readState}

    stop_ramp() { ${systemctl} --user stop century-night-ramp.service 2>/dev/null || true; }

    # Apply a step with no animation and tell waybar. This is the fallback
    # whenever systemd cannot be reached (units not activated yet, no user
    # bus), so that no subcommand is ever a silent no-op.
    apply_now() {
      ${applyStep} "$1" || true
      echo "$1" > "$PHASE_FILE"
      echo "$1" > "$TARGET_FILE"
      if [ "$1" = 0 ]; then SIDE=day; else SIDE=night; fi
      ${wallpaperScript}/bin/century-wallpaper-apply "$SIDE" 0 || true
      # Restart only — no poke. The fresh bar already comes up on current state,
      # and poking one that is still starting up kills it.
      ${reloadWaybar}
      
      
    }

    pin() {   # $1 = day|night, ramp toward it
      echo "$1" > "$STATE_FILE"
      MODE="$1"
      ${computeTarget}
      stop_ramp
      echo "$TARGET" > "$TARGET_FILE"
      if ! ${systemctl} --user restart --no-block century-night-ramp.service 2>/dev/null; then
        apply_now "$TARGET"
      fi
    }

    case "''${1:-status}" in
      init)
        # Instant, no ramp: login and home-manager activation. Safe with no
        # compositor — the step script writes files and skips every hyprctl.
        ${computeTarget}
        apply_now "$TARGET"
        ;;
      now)
        case "''${2:-}" in
          day) T=0 ;; night) T=$LAST ;;
          *) echo "usage: century-night now day|night" >&2; exit 1 ;;
        esac
        echo "''${2}" > "$STATE_FILE"
        stop_ramp
        apply_now "$T"
        ;;
      day)   pin day ;;
      night) pin night ;;
      auto)
        echo auto > "$STATE_FILE"
        MODE=auto
        stop_ramp
        if ! ${systemctl} --user start --no-block century-night-schedule.service 2>/dev/null; then
          ${computeTarget}
          apply_now "$TARGET"
        fi
        ;;
      toggle)
        P=$(cat "$PHASE_FILE" 2>/dev/null || echo 0)
        if [ "$P" -ge $(( LAST / 2 + 1 )) ]; then pin day; else pin night; fi
        ;;
      reconcile)
        if ! ${systemctl} --user start --no-block century-night-schedule.service 2>/dev/null; then
          ${computeTarget}
          apply_now "$TARGET"
        fi
        ;;
      status)
        P=$(cat "$PHASE_FILE" 2>/dev/null || echo "?")
        D=$(${isDay} 2>/dev/null || echo "?")
        if ${systemctl} --user is-active --quiet century-night-ramp.service 2>/dev/null; then R=ramping; else R=idle; fi
        [ "$D" = 1 ] && SUN=day || SUN=night
        echo "mode=$MODE phase=$P/$LAST sun=$SUN $R"
        ;;
      json)
        # waybar custom/century-night. DAY/NGT is what is APPLIED; the class
        # carries the mode so a manual pin can be styled as an override, the
        # way the hyprsunset widget marks its own manual mode.
        P=$(cat "$PHASE_FILE" 2>/dev/null || echo 0)
        case "$P" in ""|*[!0-9]*) P=0 ;; esac
        if [ "$P" -ge $(( LAST / 2 + 1 )) ]; then TEXT=NGT; SIDE=night; else TEXT=DAY; SIDE=day; fi
        if ${systemctl} --user is-active --quiet century-night-ramp.service 2>/dev/null; then
          CLASS="$SIDE ramping"; RAMP=" (ramping)"
        else
          CLASS="$SIDE"; RAMP=""
        fi
        [ "$MODE" != auto ] && CLASS="$CLASS manual"
        if [ "$MODE" = auto ]; then HINT="AUTO — follows the sun"; else HINT="MANUAL — right-click for AUTO"; fi
        printf '{"text":"%s","class":"%s","tooltip":"Night mode: %s%s\\n%s\\nclick to toggle"}\n' \
          "$TEXT" "$CLASS" "$SIDE" "$RAMP" "$HINT"
        ;;
      *)
        echo "usage: century-night {status|json|init|day|night|auto|toggle|reconcile|now day|now night}" >&2
        exit 1
        ;;
    esac
  '';

in {
  config = mkIf enabled {
    home.packages = [ scheduleScript rampScript cliScript wallpaperScript appThemeScript ];

    # The waybar stylesheet @imports this file by absolute path, and a MISSING
    # import makes GTK reject the entire provider — unstyled bars. So it must
    # exist before waybar ever starts, and it must be refreshed on every
    # rebuild: the store palette may have changed while the live copy did not.
    #
    # This deliberately does not signal waybar. A rebuild inside a live session
    # leaves the bar on the old colours for up to 5 minutes, and then the
    # reconciler notices the palette checksum moved and reloads it once. Doing
    # it here as well would mean two reloads for one rebuild.
    home.activation.centuryNightPalette = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if [ -L "${paletteLive}" ]; then
        $DRY_RUN_CMD rm -f "${paletteLive}"
      fi
      $DRY_RUN_CMD ${pkgs.coreutils}/bin/mkdir -p "$(dirname "${paletteLive}")" "${homeDir}/.cache"
      PHASE=$(cat "${phaseFile}" 2>/dev/null || echo 0)
      case "$PHASE" in ""|*[!0-9]*) PHASE=0 ;; esac
      [ "$PHASE" -gt ${toString lastStep} ] && PHASE=${toString lastStep}
      $DRY_RUN_CMD ${applyStep} "$PHASE" || true
    '';

    systemd.user.services.century-night-schedule = {
      Unit.Description = "Reconcile the century-series day/night palette with the time of day";
      Service = {
        Type = "oneshot";
        ExecStart = "${scheduleScript}/bin/century-night-schedule";
        # Same reason as the ramp: the re-assert can restart waybar when a
        # rebuild changed the palette, and it must survive this unit exiting.
        KillMode = "process";
      };
    };

    systemd.user.services.century-night-ramp = {
      Unit.Description = "Animated century-series day/night palette transition";
      Service = {
        ExecStart = "${rampScript}/bin/century-night-ramp";
        # Foreground walk, so `systemctl --user restart` retargets it and `stop`
        # cancels it.
        #
        # KillMode=process because the midpoint restarts waybar, and waybar must
        # outlive this unit. setsid detaches the session but NOT the cgroup, so
        # the default control-group kill would take the new bars down with the
        # ramp the moment it finished — the palette would change and the bar
        # would vanish. Same reasoning as hyprsunset-transition.service.
        KillMode = "process";
      };
    };

    systemd.user.timers.century-night-schedule = {
      Unit.Description = "Century-series day/night reconcile timer";
      Timer = {
        # Poll rather than fire at the boundary: it moves with the sun, and a
        # poll also recovers from suspend, a crash, a rebuild's hyprctl reload,
        # and a mode change.
        OnCalendar = [ "*:0/5" ];
        AccuracySec = "30s";
        Persistent = true;
      };
      Install.WantedBy = [ "timers.target" ];
    };
  };
}
