# ~/nixos-config/hosts/t620/default.nix
{ inputs, pkgs, lib, config, unstablePkgs, ... }:

{
  imports = [
    # Generated by the install script — replaced during nixos-install.
    ./hardware-configuration.nix

    # Top level nixos modules import.
    ../../modules/nixos/default.nix

    # Host specific disk configuration
    ./disko-config.nix
  ];

  boot.initrd.supportedFilesystems = [ "btrfs" ];

  # 4GB swap file matching the T620's 4GB RAM
  swapDevices = [
    {
      device = "/.swapvol/swapfile";
      size = 4 * 1024;
    }
  ];

  customConfig = {

    user = {
      name = "lando";
      email = "landonreekstin@gmail.com";
      shell.bash.color = "bright-cyan";
    };

    system = {
      hostName = "t620";
      stateVersion = "25.05";
      timeZone = "America/Chicago";
      locale = "en_US.UTF-8";
    };

    networking = {
      # NetworkManager handles DHCP — static IP assigned by the OpenBSD firewall
      firewall = { enable = false; }; # OpenBSD firewall handles perimeter security
    };

    # Headless server — no desktop environment
    desktop = {
      environments = [ "none" ];
      displayManager = {
        enable = false;
        type = "none";
      };
    };

    homeManager = {
      enable = true;
      themes = {
        kde = "none";
        hyprland = "none";
      };
    };

    packages = {
      nixos = with pkgs; [
        wget
        git
        vim
        htop
      ];
    };

    apps = {
      defaultBrowser = "none";
    };

    profiles = {
      gaming.enable = false;
      development.fpga-ice40.enable = false;
      development.kernel.enable = false;
    };

    services = {
      ssh.enable = true;
    };

    homelab = {
      vaultwarden = {
        enable = true;
        # Local IP — VPN/LAN access only, no public exposure
        domain = "192.168.100.104";
        port = 8222;
        signupsAllowed = false; # Enable temporarily for initial account creation
        tls.enable = false;     # No Caddy — direct port access on LAN/VPN
        # Env file must be created manually after install:
        #   /var/lib/vaultwarden/vaultwarden.env
        # Must contain at least: ADMIN_TOKEN=<value>
      };
    };

  };

  # Home Manager configuration for this host
  home-manager = lib.mkIf config.customConfig.homeManager.enable {
    extraSpecialArgs = { inherit inputs unstablePkgs; customConfig = config.customConfig; };
    users.${config.customConfig.user.name} = {};
  };

}
