# ~/nixos-config/hosts/t620/hardware-configuration.nix
#
# STUB — this file is replaced during installation.
# The real hardware-configuration.nix is generated by nixos-generate-config
# (or the install script) and will be written here automatically.
#
# To install: run scripts/install-new-host.sh on the T620.
# After first boot, run `post-install` to complete setup.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
