# ~/nixos-config/hosts/optiplex-nas/default.nix
# Importer only — this host's settings live in the per-domain files below, mirroring
# the layout of modules/nixos/.
{ ... }:

{
  imports = [
    # This will be generated by your install script.
    ./hardware-configuration.nix

    # Top level nixos modules import.
    ../../modules/nixos/default.nix

    # Host specific disk configuration
    ./disko-config.nix

    # Host configuration, one file per domain
    ./system.nix
    ./storage.nix
    ./desktop.nix
    ./apps.nix
    ./home.nix
    ./networking.nix
    ./homelab.nix
    ./profiles.nix
    ./ci.nix
  ];
}
