# ~/nixos-config/hosts/optiplex-nas/default.nix
{ inputs, pkgs, lib, config, ... }:

{
  imports = [
    # This will be generated by your install script.
    ./hardware-configuration.nix
    
    # Top level nixos modules import.
    ../../modules/nixos/default.nix

    # Host specific disk configuration
    ./disko-config.nix
  ];

  # 1. Tell the boot process to include Btrfs support
  boot.initrd.supportedFilesystems = [ "btrfs" ];

  # Define the mount options for the external HDD storage pool.
  fileSystems."/mnt/storage" = {
    # This device path comes from the partlabel we set in Disko.
    device = "/dev/disk/by-partlabel/disk-hdd1-storage";
    fsType = "btrfs";
    options = [
      # Standard options for BTRFS
      "noatime"
      "compress=zstd"
      # This is the crucial option:
      # It tells systemd not to halt the boot process if this device isn't ready.
      "nofail"
    ];
  };

  # 2. Create and enable a swap file on our dedicated swap subvolume
  swapDevices = [
    {
      device = "/.swapvol/swapfile";
      size = 8 * 1024; # 8GB swap file, adjust as needed
    }
  ];

  # === Encrypted Drive for Private Samba Share ===
  boot.initrd.systemd.enable = true; # Ensure systemd is used in initrd for handling encrypted volumes
  # copies the keyfile into the initrd so it's available at boot time
  boot.initrd.secrets."/secrets/private_luks.key" = "/root/secrets/private_luks.key";
  fileSystems."/mnt/private" = {
    fsType = "ext4";
    # This specifies the decrypted device that will be mounted.
    device = "/dev/mapper/private";
    # These options are crucial for removable drives.
    # 'nofail' prevents an error if the device isn't present at boot.
    # 'x-systemd.device-timeout=1' tells systemd to only wait 1 second
    # for the device to appear, preventing long boot delays.
    options = [ "nofail" "x-systemd.device-timeout=10s" ];

    # This section tells NixOS how to create the "/dev/mapper/private" device.
    encrypted = {
      enable = true;
      label = "private";
      # Point to the actual, physical encrypted partition.
      blkDev = "/dev/disk/by-uuid/2ec75d33-7943-47d2-a9c3-dd11d996f9f0";
      keyFile = "/secrets/private_luks.key";
    };
  };

  # === Declaratively set permissions for Samba mount points ===
  # This ensures the 'lando' user, which Samba is forced to use,
  # has the necessary permissions to read and write to the shares.
  systemd.tmpfiles.rules = [
    "d /mnt/storage 0775 lando users - -"
    "d /mnt/private 0775 lando users - -"
  ];

  # === Optiplex NAS Specific Values for `customConfig` ===
  customConfig = {
    
    user = {
      # This will be created during your installation.
      name = "lando"; # Or whatever user your script creates
      email = "landonreekstin@gmail.com";
      shell.bash.color = "bright-blue";
    };
    
    system = {
      hostName = "optiplex-nas";
      stateVersion = "25.05"; # Match your flake's version
      timeZone = "America/Chicago";
      locale = "en_US.UTF-8";
    };

    networking = {
      networkmanager = {
        enable = false; # Disable NetworkManager for static IP
      };
      staticIP = {
        enable = true;
        interface = "enp0s31f6";
        address = "192.168.1.76";
        gateway = "192.168.1.1";
      };
      firewall = { enable = false; };
    };
    
    # This is a server, so we disable the desktop environment.
    desktop = {
      environments =  [ "none" ];
      displayManager = {
        enable = false;
        type = "none";
      };
    };
    
    programs = {

    };

    homeManager = {
      enable = true;
      themes = {
        # Themes are not applicable for a headless server
        kde = "none";
        hyprland = "none";
      };
    };

    packages = {
      nixos = with pkgs; [ 
        wget
        git
        vim
        htop
        claude-code
      ];
      homeManager = with pkgs; [ 
        vscode
      ];
    };

    apps = {
      defaultBrowser = "none";
    };

    profiles = {
      gaming.enable = false;
      development.fpga-ice40.enable = false;
      development.kernel.enable = false;
    };

    services = {
      ssh.enable = true;
      vscodeServer.enable = true;
      nixai.enable = false;
    };

    homelab = {
      samba = {
        enable = true; # This keeps your original share active
        private = {
          enable = true; # This activates the new private share
          # The path defaults to /mnt/private, which is correct for this host.
          # The port defaults to 4445.
        };
      };
      jellyfin.enable = false;
      mediaSetup = {
        enable = true;
        user = config.customConfig.user.name; # This pulls "lando" from the user section
        storagePath = "/mnt/storage";
        cachePath = "/mnt/cache";
      };
    };
  };

  # Home Manager configuration for this Host
  home-manager = lib.mkIf config.customConfig.homeManager.enable {
    useGlobalPkgs = true;
    useUserPackages = true;
    backupFileExtension = "hm-backup";
    extraSpecialArgs = { inherit inputs; customConfig = config.customConfig; };
    users.${config.customConfig.user.name} = { pkgs', lib', config'', ... }: {
      imports = [
        ../../modules/home-manager/default.nix
      ];
    };
  };
  
}
